### ISSUE TITLE
shellinabox 2.20 Black Background

### ISSUE THREAD

**Issue by Andr20** [shellinabox/shellinabox#502]
Hello!
I tried to follow the readme file in options-available but i am not able to make it so that i see with the black background, i tried every change between _ + but nothing, how i make it work?

**Comment by im-zhou** [comment]
Add the following to the bottom of your "01+Color Terminal.css" file
```css
#vt100 #cursor.bright {
  background-color: white!important;
  color:            black!important;
}

#vt100 #cursor.dim {
  background-color: black!important;
}

#vt100 #scrollable {
  color:            #ffffff!important;
  background-color: #000000!important;
}

#vt100 #scrollable.inverted {
  color:            #000000!important;
  background-color: #ffffff!important;
}

#vt100 .ansiDef {
  color:            #ffffff!important;
}

#vt100 .ansiDefR {
  color:            #000000!important;
}

#vt100 .bgAnsiDef {
  background-color: #000000!important;
}

#vt100 .bgAnsiDefR {
  background-color: #ffffff!important;
}

#vt100 #scrollable.inverted .ansiDef {
  color:            #000000!important;
}

#vt100 #scrollable.inverted .ansiDefR {
  color:            #ffffff!important;
}

#vt100 #scrollable.inverted .bgAnsiDef {
  background-color: #ffffff!important;
}

#vt100 #scrollable.inverted .bgAnsiDefR {
  background-color: #000000!important;
}

```
